# Generated by Django 5.2.1 on 2025-07-09 20:48

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic_original',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_original_upload_to),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_resized_upload_to),
        ),
    ]
