# Generated by Django 5.2.1 on 2025-07-15 18:53

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_pic_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ref_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ref_pronouns',
        ),
        migrations.AlterField(
            model_name='profile',
            name='fet',
            field=models.CharField(blank=True, help_text='This is your Fetlife Username, if you have one.', max_length=100, verbose_name='fet name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='This is your diplay name on this site.  It is not your login name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic_original',
            field=models.ImageField(blank=True, help_text='This will be used during the auction', null=True, upload_to=profiles.models.profile_original_upload_to, verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref_no_words',
            field=models.TextField(blank=True, help_text='Words you prefer not to be used in an auction', verbose_name='words to avoid'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref_words',
            field=models.TextField(blank=True, help_text='Words you might like used to describe you in an auction', verbose_name='preferred words'),
        ),
    ]
