# Generated by Django 5.2.1 on 2025-07-08 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], max_length=10)),
                ('bid_from', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('short', models.TextField()),
                ('long', models.TextField(blank=True)),
                ('ready', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='scenes.auction')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='profiles.profile')),
            ],
        ),
    ]
