# Generated by Django 5.2.1 on 2025-07-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibleBidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together={('auction', 'profile')},
        ),
        migrations.AddField(
            model_name='scene',
            name='other_bidders',
            field=models.CharField(blank=True, help_text='Any other specific bidder audience not listed', max_length=200),
        ),
        migrations.AddField(
            model_name='scene',
            name='eligible_bidders',
            field=models.ManyToManyField(blank=True, to='scenes.eligiblebidder'),
        ),
        migrations.RemoveField(
            model_name='scene',
            name='bid_from',
        ),
    ]
