# Generated by Django 5.2.1 on 2025-07-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_eligiblebidder_alter_scene_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['order', 'profile__name']},
        ),
        migrations.AddField(
            model_name='scene',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls order in the projection dropdown.'),
        ),
    ]
